apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: openshift-python
  name: troubleshot
  namespace: sandbox-modolo
spec:
  failedBuildsHistoryLimit: 2
  output:
    to:
      kind: DockerImage
      name: 172.30.186.243:5000/sandbox-modolo/openshift-python
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/mrmodolo/openshift-python.git
    type: Git
  strategy:
    dockerStrategy:
    type: Docker
  successfulBuildsHistoryLimit: 2
  triggers: []
